CREATE TABLE LIVROS (
	ID						INT IDENTITY(1,1)		PRIMARY KEY,
	NOME					VARCHAR(150)			NOT NULL,
	EDITORA					VARCHAR(150)			NOT NULL,
	AUTOR					VARCHAR(150)			NOT NULL,
	PRECO					DECIMAL(10,2)			NOT NULL,
	QUANTIDADEPAGINAS		INT						NOT NULL,
	ANOEDICAO				INT				NOT NULL,
	TIPOLIVRO				VARCHAR(10)				NOT NULL,
	GENERO					VARCHAR(25)				NOT NULL,
	DATAHORACADASTRO		DATETIME				DEFAULT GETDATE(),


	CONSTRAINT CHK_TIPOLIVRO
				CHECK (TIPOLIVRO IN(
						'MOLE',
						'DURA',
						'EBOOK')),

	CONSTRAINT CHK_GENERO
				CHECK (GENERO IN (
						'FICÇÃO',
						'FANTASIA',
						'ROMANCE',
						'TERROR',
						'HQ',
						'AUTOAJUDA',
						'RELIGIÃO',
						'SOCIOLOGIA',
						'FILOSOFIA',
						'SUSPENSE')),

	CONSTRAINT CHK_PRECO
				CHECK (PRECO > 0),


	CONSTRAINT CHK_QUANTIDADE
				CHECK (QUANTIDADEPAGINAS >= 0)

);

ALTER TABLE LIVROS
	ADD	QUANTIDADE		INT		NOT NULL;


Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=BDBiblioteca;Integrated Security=True;